### PR TITLE
French, Japanese, and Spanish translations for AVAA

### PR DESCRIPTION
**Pull request by ablwr**
**Update!**
This PR outlines the framework for French, Japanese, and Spanish translated pages for the AVAA.

This does not change anything about the standard AVAA (or at least, it shouldn't), and references to the (currently in English) FR, ES, and JP versions of the site are not publicly visible on the sidebar, but can be seen at avartifactatlas.com/fr, avartifactatlas.com/es, avartifactatlas.com/jp ... you get it.

I'm doing this because there is translation interest in these languages, and people can work at their own pace by using the "Edit in Prose!" feature at the bottom of every page or by editing in GitHub and sending PRs, but we won't display the link to the translated site(s) until enough has been translated. 

To update from the previous draft... this should incorporate the Formats pages, Search, and Tags/Categories.

**Previous text**
This initial commit lays the groundwork for a Spanish translation of the AVAA.

There are now copies of every public page with -spa attached to the end. All of these pages show up when on the Spanish language site (available from the sidebar in this branch).

However, I don't speak Spanish! I did some cursory changes just so you can see what this looks like and for testing purposes, but pretty much every top-level page and the Artifact pages will all need their own translations.

Also, I didn't touch the "Formats" section since that one is still new, and I figure there will be more text added into that one sooner rather than later. We can add it in later.

Screenshot from 2020-08-08 14-44-17

cc: @DaleLore

### CODE REVIEW

**Comment by retokromer** [comment]
[FYI: Since some time (I don’t remember when this was introduced) you can flag the PR as WIP until it’s fine, which is useful to prevent too early merging.]

**Comment by ablwr** [comment]
Thanks @retokromer!

**Comment by ablwr** [comment]
@iamdamosuzuki @oceanofsound Ready for a review!

@retokromer I know you speak many languages and teach in several, as well -- if you know of groups that are interested in translating to, say, German, let me know and I can add the framework to allow for that as well.

**Comment by retokromer** [comment]
@ablwr I often work in German, French and Italian.

**Review by oceanofsound — APPROVED** [review]

**Pull request merged**
