### PR TITLE
add text to quadrants misalignment

### PR DESCRIPTION
**Pull request by retokromer**
- add short description on fixing
- change quadrant > quadrants (often they are 4)

### CODE REVIEW

**Comment by ablwr** [comment]
File name should change too?

**Comment by retokromer** [comment]
Oops! Yes, I didn’t pay attention to it.

**Comment by ablwr** [comment]
This does also change permalinks so we should try to be careful about that, but it should map to a good-enough-guess search results instead.

**Comment by retokromer** [comment]
Permalinks are melting as the permafrost does.

**Pull request merged**
