### PR TITLE
Update depenencies to later version of Jekyll

### PR DESCRIPTION
**Pull request by ablwr**
Supersedes PR #219 and #218, tested by me, the developer. I will close the other two GitHub auto-generated PRs.

### CODE REVIEW

**Comment by retokromer** [comment]
>tested by me, the developer

I personally found that bot… scary!

**Comment by ablwr** [comment]
Microsoft is watching us :eyes:

**Comment by ablwr** [comment]
Can I get a what what

**Comment by ablwr** [comment]
I just listened to the unedited version of "Can I Get A..." and I want to retract my "what what" and replace it with a "woop woop"

**Comment by iamdamosuzuki** [comment]
Does this need anything? Is there something I can do to help?

**Comment by ablwr** [comment]
You could approve and merge it. I can't merge without at least one approval.

**Comment by iamdamosuzuki** [comment]
I built this version and everything appears to be working.

**Comment by ablwr** [comment]
Cooool thanks!

**Pull request merged**
