### PR TITLE
sparkle.md - add 'velvet cloth'

### PR DESCRIPTION
**Pull request by kieranjol**
Not sure if that's what you meant - also, do you have any experience with this kind of hand cleaning? We've always been a little nervous and afraid of doing it for fear of creating scratches, but pretty sure a lot of archives do it safely with the correct technique?

### CODE REVIEW

**Comment by ablwr** [comment]
LGTM but @kfrn / @retokromer ? Would be nice to add a short thing about hand cleaning if you have advice.

**Comment by kfrn** [comment]
I've always heard them called just 'velvets', but yes, it's a velvet cloth. 

I've not done it regularly, IMO it's more effective and less risky to clean via ultrasonic or PTRs. But I think it's a viable alternative if you don't have those options. 

Also keen to hear @retokromer's thoughts!

**Comment by kfrn** [comment]
[Here's](https://www.nfsa.gov.au/preservation/guide/handbook/conservation) a link to the NFSA webpage on cleaning. They call hand cleaning with velvet "dry dust back".

**Comment by retokromer** [comment]
I am sorry, I will not have at all the time today (… but later this week). In my opinion, we should explain which tissues are fine and which aren’t. I did some posts in AMIA-L, and had a fight with Jim Lindner about an ideal solution for the richest 10% and the reality for the 90%.

**Comment by kfrn** [comment]
Yes, one must be careful with hand cleaning, it's easy to do more harm than good. I know Janice Allen strongly cautions against it. 

> I did some posts in AMIA-L, and had a fight with Jim Lindner
Jim, argue with someone? ;-)
I had a search of the archives, could not yet find the posts in question. I do have a few conversations on film cleaning bookmarked, though.

**Comment by ablwr** [comment]
Well in the meantime,

**Comment by kieranjol** [comment]
This is the only thread I could find. http://lsv.uky.edu/scripts/wa.exe?A2=ind1208&L=amia-l&F=&S=&P=106955 It's all really great info, using pec-pads, which we also use for cleaning the heads of tape decks - I didn't find any Lindner/tl:dr exchanges though.

All this info is great though, thanks @kfrn @retokromer !!

**Comment by retokromer** [comment]
I posted something about thousand-times-washed cotton tissues. I will check the details as soon as I can.

**Comment by kieranjol** [comment]
Yup, that comment is in there in the thread alright ;)

**Comment by retokromer** [comment]
Cleaning can be made manually and/or with a machine. And both can be dry and/or with a solvent (it’s summarised in slide 15 of [Before the Restoration](https://reto.ch/training/2017/20170630/Before_the_Restoration.pdf)). In practice, we use very often a combination of different techniques, not just one.

I suggest that this PR is merged. We can add more information – and caveats – later.

**Comment by ablwr** [comment]
Agreed. I will make an issue and reference this discussion.

**Pull request merged**
