### PR TITLE
add explanations

### PR DESCRIPTION
**Pull request by retokromer**
- Should we add also information about why the error actually occurs? I guess, this would help to understand the fix.
- Of course, re-digitising fixes many errors I mentioned. Yet when you have «only» the digital manifestation of the film…

### CODE REVIEW

**Comment by ablwr** [comment]
Yes, above the "Can it be fixed?" section is usually where the general description goes... Maybe it should have a "Description" header but I didn't want to change it for allllllllll the artifacts in this PR.

**Comment by retokromer** [comment]
OK, let’s put all information in the same section.
(Film warping may be fixed by chemical treatments.)

**Comment by retokromer** [comment]
P.S. – The wast majority of the issues I mentioned can be fixed by proper re-digitising. Yet, in some cases this is not necessary, and the file itself can be fixed.

**Comment by ablwr** [comment]
Is this PR more advanced than #127?

**Comment by retokromer** [comment]
Oops! This time I was sleepy: it was supposed to be only one…

**Comment by ablwr** [comment]
Woo! It's good to have peers to check up on each other's work, even if it does lead me to being clumsy up front!

**Comment by retokromer** [comment]
I don’t have the rights to try it, but I guess you can merge my `patch-1` into your `film-film-film`, if my commits are fine with you.

**Comment by retokromer** [comment]
@ablwr Regarding https://github.com/bavc/avaa/pull/126#issuecomment-303104037, for instance https://github.com/bavc/avaa/blob/master/_artifacts/audio_phase_error.md is an example, in my opinion, of the way to include additional information.

**Comment by ablwr** [comment]
Yes, I think this should be followed.

**Pull request merged**
