### PR TITLE
add analogue slip

### PR DESCRIPTION
**Pull request by retokromer**
This is a GIF showing an error during the analogue printing: the «original» film strip slipped in the gate at a cement splice.

### CODE REVIEW

**Comment by ablwr** [comment]
Hey, no troubles this time, eh?

**Comment by ablwr** [comment]
Cool GIF but please embed it into a page. :)

**Comment by retokromer** [comment]
No, with CLI it worked, this morning with GUI I got an error.

**Comment by retokromer** [comment]
Yes, I was testing if I can also upload.

**Comment by retokromer** [comment]
@ablwr Is there an official™ model™ for the page? Otherwise I will copy and modify an existing one…

**Comment by ablwr** [comment]
No, no template, although that's a good idea... Worth thinking about when someone resolves #115 (maybe I'll take that on -- although there's a few webdev bugs I want to shape up when I get a free moment).

**Comment by retokromer** [comment]
™ Indeed, _template_ was the word I could not find in my brain. The search algorithm MUST be improved.

**Comment by ablwr** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
